type Task {
  _id: ID!
  name: String!
  description: String!
  createdBy: User! @authorized(roles: [ADMIN])
}

input NewTaskInput {
  name: String!
  description: String!
}

input UpdateTaskInput {
  name: String!
  description: String!
}

extend type Query {
  tasks: [Task]! @authenticated
}

extend type Mutation {
  createTask(input: NewTaskInput!): Task!
    @authorized(roles: [ADMIN, TRAINER])
    @authenticated

  updateTask(input: UpdateTaskInput!): Task!
    @authorized(roles: [ADMIN, TRAINER])
    @authenticated

  deleteTask(input: ID!): Task!
    @authorized(roles: [ADMIN, TRAINER])
    @authenticated
}
