type Task {
  _id: ID!
  name: String!
  description: String!
  createdBy: User! @authorized(roles: [ADMIN, TRAINER])
}

input NewTaskInput {
  name: String!
  description: String!
}

input UpdateTaskInput {
  name: String
  description: String
}

extend type Query {
  task(id: ID!): Task! @authenticated
  tasks: [Task]! @authenticated
}

extend type Mutation {
  createTask(input: NewTaskInput!): Task!
    @authorized(roles: [ADMIN, TRAINER])
    @authenticated

  updateTask(id: ID!, input: UpdateTaskInput!): Task!
    @authorized(roles: [ADMIN, TRAINER])
    @authenticated

  deleteTask(id: ID!): Task! @authorized(roles: [ADMIN, TRAINER]) @authenticated
}
